### ISSUE TITLE
Issue appropriate warnings when not using latest version of `dfx`

### ISSUE THREAD

**Issue by alexabsmith** [dfinity/sdk#899] opened 2020-08-04 20:25 UTC
As discussed in 7/31 standup, we should issue appropriate warnings when using DFX_VERSION to access older or not-yet-promoted versions of dfx.

Three "flavors":
- [ ] No longer supported per #875 - prompt to `dfx upgrade`
- [ ] Outdated - prompt to `dfx upgrade`
- [ ] Not-yet-promoted - accessing an internal-only / unsupported version of `dfx`

**Comment by sesi200** [comment] 2022-10-05 08:45
duplicate of #1280

**Closed by sesi200** 2022-10-05 08:45 UTC
